import { parseMarkdown } from "./pdf/markdown-parser";
import { renderBlocksToPDF } from "./pdf/pdf-renderer";
import { STYLES } from "./pdf/pdf-styles";

/**
 * Export a single message to PDF using jsPDF native text rendering.
 * Produces small, searchable, text-based PDFs instead of rasterized screenshots.
 *
 * @param text - Raw markdown text of the message
 * @param filename - Output filename (without .pdf extension)
 * @param executiveName - Name of the executive persona (e.g. "Alexandria Voss")
 * @param executiveRole - Role of the executive (e.g. "Chief Marketing Officer (CMO)")
 */
export async function exportToPDF(
  text: string,
  filename: string,
  executiveName: string,
  executiveRole: string,
): Promise<void> {
  try {
    // Dynamic import to reduce bundle size
    const { default: jsPDF } = await import("jspdf");
    // Side-effect import: adds autoTable method to jsPDF prototype
    await import("jspdf-autotable");

    const doc = new jsPDF("p", "mm", "a4");
    let y: number = STYLES.marginTop;

    // Header: Executive name
    doc.setFont("helvetica", "normal", "bold");
    doc.setFontSize(18);
    doc.setTextColor(...STYLES.headingColor);
    doc.text(executiveName, STYLES.marginLeft, y);
    y += 7;

    // Header: Executive role
    doc.setFont("helvetica", "normal", "normal");
    doc.setFontSize(11);
    doc.setTextColor(...STYLES.mutedColor);
    doc.text(executiveRole, STYLES.marginLeft, y);
    y += 5;

    // Divider line
    doc.setDrawColor(...STYLES.dividerColor);
    doc.setLineWidth(0.5);
    doc.line(STYLES.marginLeft, y, STYLES.pageWidth - STYLES.marginRight, y);
    y += 10;

    // Parse markdown and render content blocks
    const blocks = parseMarkdown(text);
    y = renderBlocksToPDF(doc, blocks, y);

    // Footer divider
    y += 10;
    if (y + 15 > STYLES.pageHeight - STYLES.marginBottom) {
      doc.addPage();
      y = STYLES.marginTop;
    }
    doc.setDrawColor(...STYLES.dividerColor);
    doc.setLineWidth(0.5);
    doc.line(STYLES.marginLeft, y, STYLES.pageWidth - STYLES.marginRight, y);
    y += 6;

    // Footer text
    doc.setFont("helvetica", "normal", "italic");
    doc.setFontSize(STYLES.footerSize);
    doc.setTextColor(153, 153, 153);
    doc.text(
      `Generated by AI Bossy Brainz on ${new Date().toLocaleDateString()}`,
      STYLES.marginLeft,
      y,
    );

    doc.save(`${filename}.pdf`);
  } catch (error) {
    throw new Error(
      `Failed to export PDF: ${error instanceof Error ? error.message : "Unknown error"}`,
    );
  }
}
