// Re-exports from auto-generated types + app-specific convenience types.
// Source of truth: database.types.ts (auto-generated by Supabase CLI)

export type {
	Database,
	Json,
	Tables,
	TablesInsert,
	TablesUpdate,
} from "./database.types";

import type { Database } from "./database.types";

// Subscription types (app-level unions, not DB enums)
export type SubscriptionType =
	| "pending"
	| "trial"
	| "monthly"
	| "annual"
	| "lifetime";
export type SubscriptionStatus =
	| "pending"
	| "active"
	| "trialing"
	| "expired"
	| "cancelled";

// Row type aliases
export type AuditLog = Database["public"]["Tables"]["AuditLog"]["Row"];
export type User = Database["public"]["Tables"]["User"]["Row"];
export type Chat = Database["public"]["Tables"]["Chat"]["Row"];
export type DBMessage = Database["public"]["Tables"]["Message_v2"]["Row"];
export type Vote = Database["public"]["Tables"]["Vote_v2"]["Row"];
export type Document = Database["public"]["Tables"]["Document"]["Row"];
export type Suggestion = Database["public"]["Tables"]["Suggestion"]["Row"];
export type Stream = Database["public"]["Tables"]["Stream"]["Row"];
export type UserAnalytics =
	Database["public"]["Tables"]["UserAnalytics"]["Row"];
export type ExecutiveMemory =
	Database["public"]["Tables"]["ExecutiveMemory"]["Row"];
export type MessageReaction =
	Database["public"]["Tables"]["MessageReaction"]["Row"];

// Insert types
export type ChatInsert = Database["public"]["Tables"]["Chat"]["Insert"];
export type MessageInsert =
	Database["public"]["Tables"]["Message_v2"]["Insert"];
export type UserInsert = Database["public"]["Tables"]["User"]["Insert"];

// Visibility type for Chat
export type VisibilityType = "public" | "private";

// Bot type for messages
export type BotType = "alexandria" | "kim" | "collaborative";

// Reaction types
export type ReactionType =
	| "actionable"
	| "needs_clarification"
	| "ready_to_implement"
	| "save_for_later";

// Strategy Canvas types
export type StrategyCanvas =
	Database["public"]["Tables"]["StrategyCanvas"]["Row"];
export type StrategyCanvasInsert =
	Database["public"]["Tables"]["StrategyCanvas"]["Insert"];
export type ConversationSummary =
	Database["public"]["Tables"]["ConversationSummary"]["Row"];
export type ConversationSummaryInsert =
	Database["public"]["Tables"]["ConversationSummary"]["Insert"];
export type CanvasType = "swot" | "bmc" | "journey" | "brainstorm";

// Support Ticket types
export type TicketStatus = "open" | "in_progress" | "resolved" | "closed";
export type TicketPriority = "low" | "normal" | "high" | "urgent";
export type TicketCategory =
	| "bug"
	| "feature"
	| "billing"
	| "account"
	| "general";
export type SupportTicket =
	Database["public"]["Tables"]["SupportTicket"]["Row"];
export type SupportTicketInsert =
	Database["public"]["Tables"]["SupportTicket"]["Insert"];
export type SupportTicketMessage =
	Database["public"]["Tables"]["SupportTicketMessage"]["Row"];
export type SupportTicketMessageInsert =
	Database["public"]["Tables"]["SupportTicketMessage"]["Insert"];

// Landing Page CMS types
export type LandingPageContentType =
	| "text"
	| "textarea"
	| "url"
	| "color"
	| "list";
export type LandingPageSection =
	| "hero"
	| "executives"
	| "benefits"
	| "cta"
	| "theme"
	| "header"
	| "footer"
	| "checkup"
	| "faq"
	| "contact";

export interface LandingPageContent {
	id: string;
	section: LandingPageSection;
	key: string;
	value: string;
	type: LandingPageContentType;
	metadata: Json;
	updatedBy: string | null;
	createdAt: string;
	updatedAt: string;
}

export interface LandingPageContentInsert {
	id?: string;
	section: LandingPageSection;
	key: string;
	value: string;
	type?: LandingPageContentType;
	metadata?: Json;
	updatedBy?: string | null;
}

export interface LandingPageContentUpdate {
	value?: string;
	type?: LandingPageContentType;
	metadata?: Json;
	updatedBy?: string | null;
}

// TODO: Add StripeWebhookEvent type alias after running `pnpm gen:types`
// once migration 20260218000200_webhook_reliability.sql is applied:
// export type StripeWebhookEvent = Database["public"]["Tables"]["StripeWebhookEvent"]["Row"];

// Need to import Json for interfaces above
import type { Json } from "./database.types";
